### ISSUE TITLE
API: Get a list of all streams with a project public key.

### ISSUE THREAD

**Issue by cadesalaberry** [cine-io/broadcast-js-sdk#3]
I am working on a project that needs to display all streams that are running now ([here](http://nomad-live.github.io/nomad-live-dashboard/public_html/)).

But accessing the array can only be done with a **project secret key**, which also gives access to the publish password.

Is there a way to do it with the current API ?

**Comment by jeffreywescott** [comment]
Hi, @cadesalaberry. Our API doesn't currently support the ability for anyone to query the streams, because we can never be sure that our clients _want_ their streams to be publicly viewable.

**Comment by cadesalaberry** [comment]
Well technically they are always publicly viewable if I am not mistaken. One just needs to get the right ID to feed to the player.

Wouldn't it make more sense to have a boolean `private` field for each stream that would be accessible only if the user is using the **Project Secret Key** ?

Using the **Project Public Key** would then return a `401 Unauthorized` as it is doing right now.
